# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [ ]:
# Your code here

In [2]:
import numpy as np
import pandas as pd

In [3]:
customer_data = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
customer_data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [4]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [5]:
customer_data.isna()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,False,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4003,True,True,True,True,True,True,True,True,True,True,True
4004,True,True,True,True,True,True,True,True,True,True,True
4005,True,True,True,True,True,True,True,True,True,True,True
4006,True,True,True,True,True,True,True,True,True,True,True
4007,True,True,True,True,True,True,True,True,True,True,True

In [21]:
for col in customer_data.columns:
    print(f"{col}")
    print(customer_data[col].value_counts().sum())

Customer
1071
ST
1071
GENDER
954
Education
1071
Customer Lifetime Value
1068
Income
1071
Monthly Premium Auto
1071
Number of Open Complaints
1071
Policy Type
1071
Vehicle Class
1071
Total Claim Amount
1071

In [7]:
customer_data.isnull().sum()

Customer                     2937
ST                           2937
GENDER                       3054
Education                    2937
Customer Lifetime Value      2940
Income                       2937
Monthly Premium Auto         2937
Number of Open Complaints    2937
Policy Type                  2937
Vehicle Class                2937
Total Claim Amount           2937
dtype: int64

In [8]:
drop_customer_data = customer_data.dropna(subset=["Customer"])
drop_customer_data.isna()
drop_customer_data.isnull().sum()

Customer                       0
ST                             0
GENDER                       117
Education                      0
Customer Lifetime Value        3
Income                         0
Monthly Premium Auto           0
Number of Open Complaints      0
Policy Type                    0
Vehicle Class                  0
Total Claim Amount             0
dtype: int64

In [9]:
drop_customer_data_2 = drop_customer_data.fillna({"GENDER":"N/A"})

In [10]:
drop_customer_data_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     1071 non-null   object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 100.4+ KB

In [11]:
drop_customer_data_2[drop_customer_data["Customer Lifetime Value"].isnull()]

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,N/A,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
78,SP81997,Washington,F,Master,NaN,41275.0,96.0,1/0/00,Personal Auto,Four-Door Car,41.122303
988,GT62080,Washington,M,High School or Below,NaN,55561.0,63.0,1/0/00,Personal Auto,Four-Door Car,227.872071

In [12]:
drop_customer_data_3 = drop_customer_data_2.copy()
drop_customer_data_3.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,N/A,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [13]:
drop_customer_data_4 = drop_customer_data_3.copy()
drop_customer_data_4 = drop_customer_data_4.drop(0)
drop_customer_data_4["Customer Lifetime Value"] = drop_customer_data_4["Customer Lifetime Value"].str.replace("%", "")
drop_customer_data_4["Customer Lifetime Value"] = drop_customer_data_4["Customer Lifetime Value"].astype(float)
drop_customer_data_4["Customer Lifetime Value"] = drop_customer_data_4["Customer Lifetime Value"]/100
drop_customer_data_4.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
1,QZ44356,Arizona,F,Bachelor,6979.5359,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,12887.4317,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,7645.8618,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,5363.0765,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,8256.2978,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042

In [14]:
promedio_ltv = drop_customer_data_4["Customer Lifetime Value"].mean()
print(promedio_ltv)

7936.902593445694

In [19]:
drop_customer_data_5 = drop_customer_data_4.copy()
drop_customer_data_5 = drop_customer_data_5.fillna({"Customer Lifetime Value": promedio_ltv})
drop_customer_data_5.isnull().sum()

Customer                     0
ST                           0
GENDER                       0
Education                    0
Customer Lifetime Value      0
Income                       0
Monthly Premium Auto         0
Number of Open Complaints    0
Policy Type                  0
Vehicle Class                0
Total Claim Amount           0
dtype: int64

In [20]:
drop_customer_data_5.duplicated().sum()

np.int64(0)

In [26]:
drop_customer_data_5.nunique()

Customer                     1070
ST                              8
GENDER                          6
Education                       6
Customer Lifetime Value      1028
Income                        774
Monthly Premium Auto          131
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            760
dtype: int64

In [27]:
drop_customer_data_5["GENDER"].unique()

array(['F', 'M', 'N/A', 'Femal', 'Male', 'female'], dtype=object)

In [41]:
drop_customer_no_null = drop_customer_data_4.copy()
drop_customer_no_null["GENDER"] = drop_customer_data_5["GENDER"].replace({
    "female": "F",
    "Male": "M",
    "Femal": "F"
})
drop_customer_no_null["GENDER"].unique()

array(['F', 'M', 'N/A'], dtype=object)

In [42]:
drop_customer_no_null["ST"].unique()

array(['Arizona', 'Nevada', 'California', 'Washington', 'Oregon', 'Cali',
       'AZ', 'WA'], dtype=object)

In [43]:
customer_no_null = drop_customer_no_null.copy()
customer_no_null["ST"] = drop_customer_no_null["ST"].replace({
    "AZ": "Arizona",
    "WA": "Washington",
    "Cali" : "California"
})
customer_no_null["ST"].unique()

array(['Arizona', 'Nevada', 'California', 'Washington', 'Oregon'],
      dtype=object)

In [44]:
customer_no_null["Education"].unique()

array(['Bachelor', 'High School or Below', 'College', 'Master',
       'Bachelors', 'Doctor'], dtype=object)

In [45]:
customer_no_null_2 = customer_no_null.copy()
customer_no_null_2["Education"] = customer_no_null["Education"].replace({
    "Bachelors": "Bachelor",
    "College": "Bachelor"
})
customer_no_null_2["Education"].unique()

array(['Bachelor', 'High School or Below', 'Master', 'Doctor'],
      dtype=object)

In [46]:
customer_no_null_2["Vehicle Class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car'], dtype=object)

In [48]:
customer_no_null_2.sample(10)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
657,ZH19885,Washington,F,High School or Below,2514.5920,43860.0,65.0,1/0/00,Personal Auto,Four-Door Car,156.124914
953,QQ89253,Oregon,F,Bachelor,10221.8050,0.0,134.0,1/0/00,Personal Auto,SUV,643.200000
636,PT64580,Washington,M,Master,4191.9661,77048.0,103.0,1/0/00,Personal Auto,SUV,141.199465
108,EP80820,California,N/A,Bachelor,5928.7485,40531.0,74.0,1/0/00,Personal Auto,Two-Door Car,30.567357
423,RE81445,Oregon,F,Bachelor,5734.5982,98132.0,71.0,1/0/00,Personal Auto,Two-Door Car,50.587035
465,RA93608,Oregon,M,Bachelor,18073.9400,64620.0,76.0,1/1/00,Personal Auto,Two-Door Car,364.800000
409,DP84567,California,M,High School or Below,20216.3088,0.0,183.0,1/0/00,Personal Auto,Luxury SUV,878.400000
244,PP40919,California,F,Bachelor,2376.5335,0.0,91.0,1/5/00,Personal Auto,Two-Door Car,436.800000
88,CJ15590,Oregon,N/A,Bachelor,2695.1824,32720.0,67.0,1/0/00,Personal Auto,Four-Door Car,321.600000
1031,EM27919,California,M,Bachelor,4458.1134,17622.0,65.0,1/1/00,Personal Auto,Four-Door Car,312.000000

In [49]:
customer_no_null_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1070 entries, 1 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1070 non-null   object
 1   ST                         1070 non-null   object
 2   GENDER                     1070 non-null   object
 3   Education                  1070 non-null   object
 4   Customer Lifetime Value    1068 non-null   float64
 5   Income                     1070 non-null   float64
 6   Monthly Premium Auto       1070 non-null   float64
 7   Number of Open Complaints  1070 non-null   object
 8   Policy Type                1070 non-null   object
 9   Vehicle Class              1070 non-null   object
 10  Total Claim Amount         1070 non-null   float64
dtypes: float64(4), object(7)
memory usage: 100.3+ KB

In [50]:
customer_clean_col = customer_no_null_2.copy()
customer_clean_col = customer_no_null_2.rename(columns={
    "ST" : "state",
    "Customer Lifetime Value"  : "clv",
    "Number of Open Complaints"  : "Open Complaints"
})
customer_clean_col.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1070 entries, 1 to 1070
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer              1070 non-null   object
 1   state                 1070 non-null   object
 2   GENDER                1070 non-null   object
 3   Education             1070 non-null   object
 4   clv                   1068 non-null   float64
 5   Income                1070 non-null   float64
 6   Monthly Premium Auto  1070 non-null   float64
 7   Open Complaints       1070 non-null   object
 8   Policy Type           1070 non-null   object
 9   Vehicle Class         1070 non-null   object
 10  Total Claim Amount    1070 non-null   float64
dtypes: float64(4), object(7)
memory usage: 100.3+ KB

In [51]:
customer_clean_col.columns = [column_name.lower() for column_name in customer_clean_col.columns]
customer_clean_col.columns

Index(['customer', 'state', 'gender', 'education', 'clv', 'income',
       'monthly premium auto', 'open complaints', 'policy type',
       'vehicle class', 'total claim amount'],
      dtype='object')

In [71]:
customer_data_df = customer_clean_col.copy()
customer_data_df.head()

,customer,state,gender,education,clv,income,monthly premium auto,open complaints,policy type,vehicle class,total claim amount
1,QZ44356,Arizona,F,Bachelor,6979.5359,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,12887.4317,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,7645.8618,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,5363.0765,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,8256.2978,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042

In [72]:
generos = customer_data_df["gender"].value_counts()
generos

gender
F      502
M      452
N/A    116
Name: count, dtype: int64

In [73]:
states = customer_data_df["state"].value_counts()
states

state
California    331
Oregon        320
Arizona       211
Washington    110
Nevada         98
Name: count, dtype: int64

In [76]:
numeric_info = pd.DataFrame({
    "mean": customer_data_df.mean(numeric_only=True),
    "median": customer_data_df.median(numeric_only=True),
    "std": customer_data_df.std(numeric_only=True),
    "min":customer_data_df.min(numeric_only=True),
    "max":customer_data_df.max(numeric_only=True)
})

numeric_info

,mean,median,std,min,max
clv,7936.902593,5881.742350,6434.784103,2004.350700,58166.553500
income,39332.426168,36295.500000,30459.950996,0.000000,99960.000000
monthly premium auto,192.480374,82.500000,1601.748886,61.000000,35354.000000
total claim amount,405.362874,354.964564,292.905738,0.382107,2893.239678

In [86]:
customer_data_df_mpa = customer_data_df.sort_values("monthly premium auto", ascending=False)
customer_data_df_mpa

,customer,state,gender,education,clv,income,monthly premium auto,open complaints,policy type,vehicle class,total claim amount
44,YD87931,Washington,M,Doctor,4951.6561,46896.0,35354.0,1/1/00,Personal Auto,Four-Door Car,31.707317
856,QZ77637,Washington,F,Bachelor,11665.0978,84978.0,35353.0,1/1/00,Corporate Auto,Four-Door Car,166.772960
747,JT11876,Washington,F,High School or Below,5435.7678,0.0,10202.0,1/0/00,Personal Auto,Four-Door Car,626.116259
354,CI38330,Washington,M,Bachelor,2549.7861,72217.0,6464.0,1/0/00,Personal Auto,Four-Door Car,91.146661
869,ER19995,Washington,F,Bachelor,17786.2778,99790.0,6464.0,1/0/00,Personal Auto,Four-Door Car,178.986788
...,...,...,...,...,...,...,...,...,...,...,...
436,HX74855,Washington,M,High School or Below,2471.5284,95697.0,61.0,1/0/00,Personal Auto,Two-Door Car,114.273025
983,ES90681,California,F,Bachelor,2417.7600,51808.0,61.0,1/1/00,Personal Auto,Four-Door Car,351.149904
601,WO29605,Oregon,F,Bachelor,2436.8751,48875.0,61.0,1/0/00,Personal Auto,Two-Door Car,1.838367
406,TR67616,Oregon,M,High School or Below,4731.3670,30686.0,61.0,1/0/00,Corporate Auto,Four-Door Car,19.938981
805,LA14484,Nevada,M,High School or Below,2227.0728,27972.0,61.0,1/0/00,Special Auto,Four-Door Car,292.800000

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [88]:
top_5_less_common = (
    customer_data_df["state"]
    .value_counts()
    .sort_values()
    .head(5)
)

top_5_less_common

state
Nevada         98
Washington    110
Arizona       211
Oregon        320
California    331
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [91]:
policy_resume = (
    customer_data_df["policy type"]
    .value_counts()
    .sort_values(ascending=False)
)
policy_resume

policy type
Personal Auto     779
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [106]:
personal_auto_df = customer_data_df.loc[customer_data_df["policy type"] == "Personal Auto"]
corporate_auto_df = customer_data_df.loc[customer_data_df["policy type"] == "Corporate Auto"]

avg_personal = personal_auto_df["income"].mean()
avg_corporate = corporate_auto_df["income"].mean()

print(f"For Personal Auto : $ {avg_personal:.2f}")
print(f"For Corporate Auto : $ {avg_corporate:.2f}")

For Personal Auto : $ 38229.71
For Corporate Auto : $ 41390.31

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your code here